pipeline {
    agent { label 'master' }
    tools {
  terraform 'terraform2'
}
stages {
        stage('terraform format check') {
            steps{
               sh 'terraform -chdir=./terraform/ fmt'
            }
        }
        stage('terrafrom init'){
            steps{
                withAWS(credentials: 'myaccess') {
                    sh 'terraform -chdir=./terraform/ init'
                }
            }
        }
            stage('terrafrom apply'){
                steps{
                    withAWS(credentials: 'myaccess') {
                         sh 'terraform -chdir=./terraform/ apply --var-file=dev.tfvars --auto-approve'
                    }
                }
            }
    }
}